
version: '3.8'

services:
  rabbitmq_ecossistem:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-django-ecossistem
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_ecossistem:/var/lib/rabbitmq

volumes:
  rabbitmq_ecossistem:
