# Generated by Django 5.2.6 on 2025-09-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="ProdutoMirror",
            fields=[
                ("sku", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.IntegerField()),
            ],
        ),
    ]
