# Generated by Django 5.2.7 on 2025-10-02 21:17

import dj_cqrs.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMirror',
            fields=[
                ('cqrs_revision', models.IntegerField()),
                ('cqrs_updated', models.DateTimeField()),
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(dj_cqrs.mixins.RawReplicaMixin, models.Model),
        ),
    ]
